const ActionType = {
    All_PRODUCT_FAIL:"All_PRODUCT_FAIL",
    All_PRODUCT_REQUESTED:"All_PRODUCT_REQUESTED",
    All_PRODUCT_SUCCESS:"All_PRODUCT_SUCCESS",
    CLEAR_ERRORS:"CLEAR_ERRORS",

    PRODUCT_DETAIL_FAIL:"PRODUCT_DETAIL_FAIL",
    PRODUCT_DETAIL_REQUESTED:"PRODUCT_DETAIL_REQUESTED",
    PRODUCT_DETAIL_SUCCESS:"PRODUCT_DETAIL_SUCCESS",

    USER_REQUEST:"USER_REQUEST",
    USER_REQUEST_SUCCESS:"USER_REQUEST_SUCCESS",
    USER_REQUEST_FAIL:"USER_REQUEST_FAIL",

    LOAD_USER_REQUEST:"LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS:"LOAD_USER_SUCCESS",
    LOAD_USER_FAIL:"LOAD_USER_FAIL",

}
export default ActionType